from CV_Matching import rank_applicants
 
applicants=[  {
        "email": "applicant@gmail.com",
        "password": "123456",
        "resume": "\n\nContact\nEducation\n+923101404487\nPhone\nhafizzabdullah999@gmail.com\nEmail\nwww.linkedin.com/in/hafiz-muhammad-\nabdullah-\nLinkedin\nMUHAMMAD ABDULLAH\nSOFTWARE ENGINEER\nI  am  a  Software  Engineering  student  at  Comsats  University  Lahore,\nThroughout  my  degree,  I  have  acquired  proficiency  in  programming,\nobject-oriented  programming  (OOP),  data  structures,  algorithms,  and\ndatabases. My focus has been on building a solid foundation in these\nareas.\nProjects\nComsats University Lahore Campus\nPunjab Group of Colleged\nSoftware Engineering\nICS\n2020-present\n2018-2020\nHTML/CSS\nSQL\nNoSQL\nEnglish\nUrdu\nSkills\nLanguage\nJavaScript\nReact.Js\nNode.Js\nC\nUser Authentication In Mern\nFeatures: User Sign Up , Sign up with google (oauth 20) , JWT\n(javascript web token) storing in the user's browser , User Sign In\nusing JWT , Showing dashboard on Sign In.\nE-Commerce website in MERN\nFeatures: Product  Listing,  Product  Details,Add  to  Cart,\nDelete from Cart, Update Cart, Persistent Cart Storage using\ncookie, Remove Items from Cart, Checkout:\nLearnify app in React native and Firebase\nStudent: Registration  ,  Login  ,  view  teachers  list  ,  make\nappointment , realtime chat , change profile , reset password\nTeacher:  Registration , Login , accept/remove hiring request\n, change profile info , reset password.\nGym Management System using Linked List in C\nFeatures: Member SignUp , Login , change password , change\nname , pay fee.\nAdmin  login  ,  see  all  members  ,  search  by  name  ,  delete\nmember , check fee status.\nRestaurant Management System Database (SQL Server)\nFeatures: Database Schema , Queries , Procedures , triggers\n,Views \nhttps://github.com/MuhammadAbdullah9999\nGithub\nSmart HRM (FYP in progress)\nDescription: HR and Payroll system with CV matching with Job\ndescription using ML model."
    },
            {
        "email": "applicant2@gmail.com",
        "password": "123456",
        "resume": "\n\nContact\nEducation\n+923101404487\nPhone\nhafizzabdullah999@gmail.com\nEmail\nwww.linkedin.com/in/hafiz-muhammad-\nabdullah-\nLinkedin\nMUHAMMAD ABDULLAH\nSOFTWARE ENGINEER\nI  am  a  Software  Engineering  student  at  Comsats  University  Lahore,\nThroughout  my  degree,  I  have  acquired  proficiency  in  programming,\nobject-oriented  programming  (OOP),  data  structures,  algorithms,  and\ndatabases."
    }
]
job_description="i need a programming , OOP , data structures and database person"

applicants1=["\n\nContact\nEducation\n+923101404487\nPhone\nhafizzabdullah999@gmail.com\nEmail\nwww.linkedin.com/in/hafiz-muhammad-\nabdullah-\nLinkedin\nMUHAMMAD ABDULLAH\nSOFTWARE ENGINEER\nI  am  a  Software  Engineering  student  at  Comsats  University  Lahore,\nThroughout  my  degree,  I  have  acquired  proficiency  in  programming,\nobject-oriented  programming  (OOP),  data  structures,  algorithms,  and\ndatabases. My focus has been on building a solid foundation in these\nareas.\nProjects\nComsats University Lahore Campus\nPunjab Group of Colleged\nSoftware Engineering\nICS\n2020-present\n2018-2020\nHTML/CSS\nSQL\nNoSQL\nEnglish\nUrdu\nSkills\nLanguage\nJavaScript\nReact.Js\nNode.Js\nC\nUser Authentication In Mern\nFeatures: User Sign Up , Sign up with google (oauth 20) , JWT\n(javascript web token) storing in the user's browser , User Sign In\nusing JWT , Showing dashboard on Sign In.\nE-Commerce website in MERN\nFeatures: Product  Listing,  Product  Details,Add  to  Cart,\nDelete from Cart, Update Cart, Persistent Cart Storage using\ncookie, Remove Items from Cart, Checkout:\nLearnify app in React native and Firebase\nStudent: Registration  ,  Login  ,  view  teachers  list  ,  make\nappointment , realtime chat , change profile , reset password\nTeacher:  Registration , Login , accept/remove hiring request\n, change profile info , reset password.\nGym Management System using Linked List in C\nFeatures: Member SignUp , Login , change password , change\nname , pay fee.\nAdmin  login  ,  see  all  members  ,  search  by  name  ,  delete\nmember , check fee status.\nRestaurant Management System Database (SQL Server)\nFeatures: Database Schema , Queries , Procedures , triggers\n,Views \nhttps://github.com/MuhammadAbdullah9999\nGithub\nSmart HRM (FYP in progress)\nDescription: HR and Payroll system with CV matching with Job\ndescription using ML model.","\n\nContact\nEducation\n+923101404487\nPhone\nhafizzabdullah999@gmail.com\nEmail\nwww.linkedin.com/in/hafiz-muhammad-\nabdullah-\nLinkedin\nMUHAMMAD ABDULLAH\nSOFTWARE ENGINEER\nI  am  a  Software  Engineering  student  at  Comsats  University  Lahore,\nThroughout  my  degree,  I  have  acquired  proficiency  in  programming,\nobject-oriented  programming  (OOP),  data  structures,  algorithms,  and\ndatabases."
]

data=rank_applicants(job_description,applicants)
print(data)
# for resume in applicants:
#     print(resume['resume'])